### ISSUE TITLE
jsfiddle example not working in Firefox 42.0a1 (2015-07-30)

### ISSUE THREAD

**Issue by henriknorberg** [vmysla/IFRAMEr#1]
![iframe](https://cloud.githubusercontent.com/assets/1235042/9017349/27e77e1e-378b-11e5-8e1f-76f978358613.PNG)

**Comment by vmysla** [comment]
Thank you! 
I'm not surprised, as not working demos  - also are part of our reality :)

Please check out the latest version of the demo page:
https://jsfiddle.net/vmysla/7rhgoeuq/3/embedded/result/
It should be fine now.
